import Head from 'next/head'
import Image from 'next/image'
import localFont from 'next/font/local'
import styles from '@/styles/Home.module.css'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
})

export default function Home() {
    return (
        <>
            <Head>
                <title>Welcome to Ness Store</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <Image
                        className={styles.logo}
                        src='https://nextjs.org/icons/next.svg'
                        alt='Next.js logo'
                        width={180}
                        height={38}
                        priority
                    />
                    <ol>
                        <li>Get started by viewing product </li>
                        <li>What are you waiting for? cmon!</li>
                    </ol>

                    <div className={styles.ctas}>
                        <a
                            href='https://yakultnes.carrd.co/'
                            target='_blank'
                            rel='noopener noreferrer'
                            className={styles.primary}
                        >
                            Not quite what you&apos;re looking for? you can
                            check my porto
                        </a>
                    </div>
                </main>
            </div>
        </>
    )
}
